### PR TITLE
Additional hyperbeam-related fixed to beamformer code

### PR DESCRIPTION
**Pull request by bwmeyers**
Needed to also change how the FEEBeam structs are created.

### CODE REVIEW

**Comment by bwmeyers** [comment]
wait wait my bad, I forgot to merge my other fix in here...

**Comment by bwmeyers** [comment]
Ok, _now_ it's ready to review :stuck_out_tongue:

**Review by robotopia — APPROVED** [review]
It's been too long for me to look at this and confirm that this is correct, but if it squares with what's currently done in VCSBeam and is compliant with Chris's documentation for Hyperdrive -- which I believe you've already checked -- then that's good enough for me.

**Comment by bwmeyers** [comment]
Yes, and it compiles which is an extra good sign.

**Pull request merged**
