### PR TITLE
Created new functions to make pulsar db access and searching simpler

### PR DESCRIPTION
**Pull request by keegansmith21**
Made 2 new functions:

- get_db_auth_addr(): gets the web address of the pulsar database and the user's authentication details

- get_filetypes_from_db: grabs the names of all the specified filetypes for a pulsar & obsid combination from the pulsar db

### CODE REVIEW

**Comment by keegansmith21** [comment]
> What happens if the function returns None, does it give a long confusing error? If so you may want to make it exit instead
Which function?

**Comment by NickSwainston** [comment]
get_db_auth_addr

**Comment by keegansmith21** [comment]
> get_db_auth_addr

The function will return auth as None. Whenever this function is called it should be up to whoever is using it to decide what to do when this occurs. I didn't put an exit in this function as it only serves as a utility and not a workflow. It's easy to type "if auth is None: sys.exit()" if that's what you want to do

**Comment by NickSwainston** [comment]
Well if it returns None then breaks, it's basically existing but in a messy way so you may as well put use exit

**Comment by keegansmith21** [comment]
> Well if it returns None then breaks, it's basically existing but in a messy way so you may as well put use exit

Nothing breaks in the function if an auth isn't found. Something will break if you try to call a client function with a None though, but it is poor coding practice to force the system to exit in a function like this. You may not necessarily want to stop everything just because you can't access the database, it depends on the case. Hence why it's better if the person using the function writes their code around this possibility and handles the case themselves

**Comment by keegansmith21** [comment]
Please see new commit @NickSwainston

**Pull request merged**
